# Generated by Django 4.2.4 on 2023-09-26 06:56

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sbmtAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Student Assignment', max_length=100)),
                ('file', models.FileField(upload_to='student/submitAssignments')),
                ('assignment_file', models.FileField(upload_to=student.models.sbmtAssignment.custom_file_name)),
            ],
        ),
    ]
