# Generated by Django 4.2.4 on 2023-09-26 07:03

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_sbmtassignment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbmtassignment',
            name='assignment_file',
        ),
        migrations.AlterField(
            model_name='sbmtassignment',
            name='file',
            field=models.FileField(upload_to=student.models.sbmtAssignment.custom_file_name),
        ),
    ]
