# Generated by Django 4.2.4 on 2023-09-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_sbmtassignment_assignment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbmtassignment',
            name='aId',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
