# Generated by Django 4.2.4 on 2023-09-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_sbmtassignment_aid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbmtassignment',
            name='aId',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
