# Generated by Django 4.2.4 on 2023-09-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_sbmtassignment_aid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbmtassignment',
            name='aId',
            field=models.CharField(default='id', max_length=10, null=True),
        ),
    ]
