# Generated by Django 4.2.4 on 2023-09-27 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_sbmtassignment_aid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbmtassignment',
            name='aId',
        ),
    ]
