# Generated by Django 4.2.4 on 2023-09-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_sbmtassignment_assignmentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='thoughts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoughtOfDay', models.TextField()),
            ],
        ),
    ]
