# Generated by Django 4.2.4 on 2023-09-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_thoughts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoughts',
            name='thoughtOfDay',
            field=models.CharField(max_length=300),
        ),
    ]
