# Generated by Django 4.2.4 on 2023-09-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_complain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
