# Generated by Django 4.2.4 on 2023-09-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_complain_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complain',
            new_name='complaint',
        ),
    ]
