# Generated by Django 5.0 on 2024-02-17 04:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_rename_complain_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(null=True)),
                ('responce', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='chatBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('chats', models.ManyToManyField(blank=True, to='student.chat')),
            ],
        ),
    ]
