# Generated by Django 5.0 on 2024-02-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_chat_chatbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbase',
            name='name',
            field=models.TextField(default='Could not load title', max_length=50),
        ),
    ]
