# Generated by Django 4.2.4 on 2023-09-19 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_batch_alter_contact_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='signUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('pswrd', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('sBatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.batch')),
            ],
        ),
    ]
