# Generated by Django 4.2.4 on 2023-09-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_signup_signupmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
