# Generated by Django 4.2.4 on 2023-09-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_signupmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='check/images')),
            ],
        ),
    ]
