# Generated by Django 4.2.4 on 2023-09-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_checkform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='checkform',
        ),
    ]
