# Generated by Django 4.2.4 on 2023-09-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_delete_checkform'),
    ]

    operations = [
        migrations.CreateModel(
            name='logInModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pswrd', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='image',
            field=models.ImageField(default=None, upload_to='student/images'),
        ),
    ]
