# Generated by Django 4.2.4 on 2023-09-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_loginmodel_alter_signupmodel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logInModel',
        ),
        migrations.AddField(
            model_name='signupmodel',
            name='address',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
