# Generated by Django 4.2.4 on 2023-09-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_delete_loginmodel_signupmodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='college',
            field=models.CharField(default='Not Available', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='signupmodel',
            name='qualification',
            field=models.CharField(default='Not Available', max_length=20, null=True),
        ),
    ]
