# Generated by Django 4.2.4 on 2023-09-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_signupmodel_college_signupmodel_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='address',
            field=models.CharField(default='Not Available', max_length=100, null=True),
        ),
    ]
