# Generated by Django 4.2.4 on 2023-09-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_signupmodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='address',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='college',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='qualification',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
