# Generated by Django 4.2.4 on 2023-09-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_signupmodel_address_alter_signupmodel_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupmodel',
            name='sBatch',
        ),
        migrations.AddField(
            model_name='signupmodel',
            name='sBatch',
            field=models.ManyToManyField(to='user.batch'),
        ),
    ]
