# Generated by Django 4.2.4 on 2023-09-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_signupmodel_sbatch_signupmodel_sbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='discription',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='batch',
            name='icon',
            field=models.ImageField(default=None, upload_to='user/batches'),
        ),
        migrations.AddField(
            model_name='batch',
            name='price',
            field=models.IntegerField(default=None),
        ),
    ]
