# Generated by Django 4.2.4 on 2023-09-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_batch_discription_batch_icon_batch_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='discription',
            field=models.TextField(default='Not filled'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='icon',
            field=models.ImageField(null=True, upload_to='user/batches'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='price',
            field=models.IntegerField(default='000'),
        ),
    ]
