# Generated by Django 4.2.4 on 2023-09-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_batch_discription_alter_batch_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='discription',
        ),
        migrations.AddField(
            model_name='batch',
            name='about',
            field=models.TextField(default='Not filled', max_length=500),
        ),
    ]
