# Generated by Django 4.2.4 on 2023-09-23 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_remove_batch_about_remove_batch_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
