# Generated by Django 4.2.4 on 2023-09-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='about',
            field=models.TextField(default='Not filled', max_length=500),
        ),
    ]
