# Generated by Django 4.2.4 on 2023-09-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_batch_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='icon',
            field=models.ImageField(null=True, upload_to='user/batches'),
        ),
    ]
