# Generated by Django 4.2.4 on 2023-09-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_batch_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='icon',
            field=models.ImageField(null=True, upload_to='student/batches/images'),
        ),
    ]
