# Generated by Django 4.2.4 on 2023-09-24 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_batch_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='bTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
