# Generated by Django 4.2.4 on 2023-09-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_batch_btime'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vTitle', models.CharField(default=None, max_length=100)),
                ('vUrl', models.URLField()),
                ('vDuration', models.DurationField()),
            ],
        ),
    ]
