# Generated by Django 4.2.4 on 2023-09-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_batch_moredescriptin'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='advantages',
            field=models.TextField(default='...'),
        ),
    ]
