# Generated by Django 4.2.4 on 2023-09-24 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_alter_batch_previewvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='previewVideo',
        ),
    ]
