# Generated by Django 4.2.4 on 2023-09-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_remove_batch_previewvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='previewVideo',
            field=models.URLField(default='https://example.com/default_video_url'),
        ),
    ]
