# Generated by Django 4.2.4 on 2023-09-24 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.instructor'),
        ),
    ]
