# Generated by Django 4.2.4 on 2023-09-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_batch_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vUrl',
            field=models.CharField(max_length=100),
        ),
    ]
