# Generated by Django 4.2.4 on 2023-09-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_alter_video_vurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='batch',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
