# Generated by Django 4.2.4 on 2023-09-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_batch_discount_alter_batch_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='discount',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
