# Generated by Django 4.2.4 on 2023-09-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_alter_batch_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
