# Generated by Django 4.2.4 on 2023-09-25 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_alter_batch_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
