# Generated by Django 4.2.4 on 2023-09-25 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_video_vdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='bnotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nTitle', models.CharField(default='Notification:', max_length=20, null=True)),
                ('notification', models.TextField()),
                ('nDate', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
