# Generated by Django 4.2.4 on 2023-09-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_bnotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='notifications',
            field=models.ManyToManyField(default=None, to='user.bnotifications'),
        ),
    ]
