# Generated by Django 4.2.4 on 2023-09-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_batch_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='sMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('about', models.TextField(default='For development purpose')),
                ('image', models.ImageField(upload_to='StudyMaterial/images')),
                ('File', models.FileField(upload_to='StudyMaterial/Files')),
            ],
        ),
    ]
