# Generated by Django 4.2.4 on 2023-09-25 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_smaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smaterial',
            name='File',
        ),
        migrations.AddField(
            model_name='batch',
            name='timings',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='smaterial',
            name='file',
            field=models.FileField(default='StudyMaterial/Files/notAvailable.jpg', upload_to='StudyMaterial/Files'),
        ),
    ]
