# Generated by Django 4.2.4 on 2023-09-25 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_remove_smaterial_file_batch_timings_smaterial_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Assignmet ', max_length=100)),
                ('file', models.FileField(default=None, upload_to='assignment/given')),
                ('submitDate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
