# Generated by Django 4.2.4 on 2023-09-26 06:48

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='sbmtAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Student Assignment', max_length=100)),
                ('file', models.FileField(upload_to='student/submitAssignments')),
                ('assignment_file', models.FileField(upload_to=user.models.sbmtAssignment.custom_file_name)),
            ],
        ),
    ]
