# Generated by Django 4.2.4 on 2023-09-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_sbmtassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='submittedAssignment',
            field=models.ManyToManyField(default=None, null=True, to='user.sbmtassignment'),
        ),
    ]
