# Generated by Django 4.2.4 on 2023-09-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('user', '0056_alter_signupmodel_submittedassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sbmtAssignment',
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='submittedAssignment',
            field=models.ManyToManyField(blank=True, to='student.sbmtassignment'),
        ),
    ]
