# Generated by Django 4.2.4 on 2023-09-26 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_alter_assignments_submitdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='submitDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
