# Generated by Django 5.0 on 2024-02-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_chat_chatbase'),
        ('user', '0064_batch_enotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='pchats',
            field=models.ManyToManyField(blank=True, to='student.chatbase'),
        ),
    ]
